const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
const PRODUCT_FETCH_FAILURE = "PRODUCT_FETCH_FAILURE";

const INCREASE_QUANTITY = "INCREASE_QUANTITY";
const DECREASE_QUANTITY = "DECREASE_QUANTITY";

export { PRODUCT_FETCH_SUCCESS, PRODUCT_FETCH_FAILURE, INCREASE_QUANTITY, DECREASE_QUANTITY };
